#!/bin/bash

java -Dsun.net.spi.nameservice.provider.1=dns,sun -classpath ".:WubbleWorld.jar:lib/mysql-connector-java-3.1.14-bin.jar:lib/jgn.jar:lib/FengGUI.jar:lib/gluegen-rt.jar:lib/jogl.jar:lib/odejava-jni.jar:lib/jme-audio.jar:lib/jme-terrain.jar:lib/jme-physics.jar:lib/jme.jar:lib/jme-awt.jar:lib/jme-collada.jar:lib/jme-gamestates.jar:lib/jme-scene.jar:lib/jme-model.jar:lib/lwjgl.jar:lib/jdom.jar" -Djava.library.path="natives/" edu.isi.wubble.jgn.rpg.RPGServer $1 
